### ISSUE TITLE
Errors when trying to build on Windows with MSYS2

### ISSUE THREAD

**Issue by Aidoboy** [jpbarrette/curlpp#41]
[Here's a Gist of the build log.](https://gist.github.com/Aidoboy/78c5b1124b5a5240d88fab91915161a9) 
[Here's my repo I'm trying to compile](https://github.com/Aidoboy/discord-aidobot)

Does anyone know what's going on? Cmake loads properly, but then I get all the stuff seen in the gist. I don't even know where to start!

**Comment by cronnosli** [comment]
The curlpp has changed since the versioned link you are using, several bugs was corrected. I would advise you to change the version that you link on your repository.

The file config.win32.h  try to define STDC_HEADERS

```
/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS
```

But it was already defined by 
C:/msys64/mingw64/include/c++/6.2.0/x86_64-w64-mingw32/bits/c++config.h:1328

`#define STDC_HEADERS 1`

If change to a more recent curlpp clone is not possible, you could clone that version to your repository and change the code in  config.win32.h to:

```
#ifndef STDC_HEADERS
/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS
#endif /* STDC_HEADERS */
```

**Comment by Aidoboy** [comment]
Woops. I forget that submodules don't automatically update.
